### ISSUE TITLE
Program didn't save the file correctly

### ISSUE THREAD

**Issue by noskill24** [CatShot112/APEX.PropertyEditor#1]
Does not work on some files from the latest version of COTW.
For example: The program loads "global_animal_types.blo" file correctly but save file is empty.
Unable to save that file.

**Comment by CatShot112** [comment]
Please check if new release is working with that file. Version 0.1.0 can save only RTPC V2 and the file You provided is RTPC V1.

**Comment by noskill24** [comment]
It seems working now. Thanks for patching!
